//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Develop\Open-SCPI-Protocol-Emulator\ProtocolParser\Keysight3458\Keysight3458ASCPI.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ProtocolParser.Keysight3458A {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public partial class Keysight3458ASCPILexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, ConfigureVoltage=5, ConfigureCurrent=6, 
		MeasureCurrent=7, MeasureVoltage=8, AC=9, DC=10, AUTO=11, MIN=12, MAX=13, 
		DEF=14, Space=15, CommaSeparator=16, QuestionMark=17, Number=18;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "ConfigureVoltage", "ConfigureCurrent", 
		"MeasureCurrent", "MeasureVoltage", "ConfigureSubsystem", "MeasureSubsystem", 
		"Current", "Voltage", "Text", "Impedance", "AC", "DC", "AUTO", "MIN", 
		"MAX", "DEF", "SingleSpace", "Space", "Comma", "CommaSeparator", "QuestionMark", 
		"Colon", "Number", "DecimalExponent", "DecimalDigits"
	};


	public Keysight3458ASCPILexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public Keysight3458ASCPILexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'*IDN?'", "'READ?'", "'ABOR'", "'ABORt'", null, null, null, null, 
		"'AC'", "'DC'", "'AUTO'", "'MIN'", "'MAX'", "'DEF'", null, null, "'?'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "ConfigureVoltage", "ConfigureCurrent", 
		"MeasureCurrent", "MeasureVoltage", "AC", "DC", "AUTO", "MIN", "MAX", 
		"DEF", "Space", "CommaSeparator", "QuestionMark", "Number"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Keysight3458ASCPI.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static Keysight3458ASCPILexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\x14', '\x108', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', '\x5', '\x3', 
		'\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x3', '\x6', '\x5', '\x6', '\\', '\n', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', 'w', '\n', '\n', '\x3', '\v', 
		'\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', 
		'\x84', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x5', '\f', '\x95', '\n', '\f', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', 
		'\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x5', '\r', '\xA6', '\n', '\r', '\x3', '\xE', '\x3', '\xE', 
		'\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', 
		'\x5', '\xF', '\xBE', '\n', '\xF', '\x3', '\x10', '\x3', '\x10', '\x3', 
		'\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x15', '\x3', '\x16', '\x3', '\x16', '\x3', '\x17', '\x6', '\x17', '\xDA', 
		'\n', '\x17', '\r', '\x17', '\xE', '\x17', '\xDB', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x19', '\x5', '\x19', '\xE1', '\n', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x5', '\x19', '\xE5', '\n', '\x19', '\x3', '\x1A', '\x3', 
		'\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', '\x1C', '\x3', '\x1C', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1C', '\x5', '\x1C', '\xF0', '\n', '\x1C', 
		'\x5', '\x1C', '\xF2', '\n', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1D', '\x3', 
		'\x1D', '\x3', '\x1D', '\x5', '\x1D', '\xFD', '\n', '\x1D', '\x3', '\x1D', 
		'\x6', '\x1D', '\x100', '\n', '\x1D', '\r', '\x1D', '\xE', '\x1D', '\x101', 
		'\x3', '\x1E', '\x6', '\x1E', '\x105', '\n', '\x1E', '\r', '\x1E', '\xE', 
		'\x1E', '\x106', '\x2', '\x2', '\x1F', '\x3', '\x3', '\x5', '\x4', '\a', 
		'\x5', '\t', '\x6', '\v', '\a', '\r', '\b', '\xF', '\t', '\x11', '\n', 
		'\x13', '\x2', '\x15', '\x2', '\x17', '\x2', '\x19', '\x2', '\x1B', '\x2', 
		'\x1D', '\x2', '\x1F', '\v', '!', '\f', '#', '\r', '%', '\xE', '\'', '\xF', 
		')', '\x10', '+', '\x2', '-', '\x11', '/', '\x2', '\x31', '\x12', '\x33', 
		'\x13', '\x35', '\x2', '\x37', '\x14', '\x39', '\x2', ';', '\x2', '\x3', 
		'\x2', '\x3', '\x4', '\x2', 'G', 'G', 'g', 'g', '\x2', '\x10D', '\x2', 
		'\x3', '\x3', '\x2', '\x2', '\x2', '\x2', '\x5', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\a', '\x3', '\x2', '\x2', '\x2', '\x2', '\t', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '\v', '\x3', '\x2', '\x2', '\x2', '\x2', '\r', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\xF', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x11', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1F', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '!', '\x3', '\x2', '\x2', '\x2', '\x2', '#', '\x3', '\x2', 
		'\x2', '\x2', '\x2', '%', '\x3', '\x2', '\x2', '\x2', '\x2', '\'', '\x3', 
		'\x2', '\x2', '\x2', '\x2', ')', '\x3', '\x2', '\x2', '\x2', '\x2', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x2', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x2', '\x33', '\x3', '\x2', '\x2', '\x2', '\x2', '\x37', '\x3', '\x2', 
		'\x2', '\x2', '\x3', '=', '\x3', '\x2', '\x2', '\x2', '\x5', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\a', 'I', '\x3', '\x2', '\x2', '\x2', '\t', 'N', 
		'\x3', '\x2', '\x2', '\x2', '\v', '[', '\x3', '\x2', '\x2', '\x2', '\r', 
		']', '\x3', '\x2', '\x2', '\x2', '\xF', '\x61', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x65', '\x3', '\x2', '\x2', '\x2', '\x13', 'v', '\x3', '\x2', 
		'\x2', '\x2', '\x15', '\x83', '\x3', '\x2', '\x2', '\x2', '\x17', '\x94', 
		'\x3', '\x2', '\x2', '\x2', '\x19', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\x1B', '\xA7', '\x3', '\x2', '\x2', '\x2', '\x1D', '\xBD', '\x3', '\x2', 
		'\x2', '\x2', '\x1F', '\xBF', '\x3', '\x2', '\x2', '\x2', '!', '\xC2', 
		'\x3', '\x2', '\x2', '\x2', '#', '\xC5', '\x3', '\x2', '\x2', '\x2', '%', 
		'\xCA', '\x3', '\x2', '\x2', '\x2', '\'', '\xCE', '\x3', '\x2', '\x2', 
		'\x2', ')', '\xD2', '\x3', '\x2', '\x2', '\x2', '+', '\xD6', '\x3', '\x2', 
		'\x2', '\x2', '-', '\xD9', '\x3', '\x2', '\x2', '\x2', '/', '\xDD', '\x3', 
		'\x2', '\x2', '\x2', '\x31', '\xE0', '\x3', '\x2', '\x2', '\x2', '\x33', 
		'\xE6', '\x3', '\x2', '\x2', '\x2', '\x35', '\xE8', '\x3', '\x2', '\x2', 
		'\x2', '\x37', '\xF1', '\x3', '\x2', '\x2', '\x2', '\x39', '\xFC', '\x3', 
		'\x2', '\x2', '\x2', ';', '\x104', '\x3', '\x2', '\x2', '\x2', '=', '>', 
		'\a', ',', '\x2', '\x2', '>', '?', '\a', 'K', '\x2', '\x2', '?', '@', 
		'\a', '\x46', '\x2', '\x2', '@', '\x41', '\a', 'P', '\x2', '\x2', '\x41', 
		'\x42', '\a', '\x41', '\x2', '\x2', '\x42', '\x4', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\x44', '\a', 'T', '\x2', '\x2', '\x44', '\x45', '\a', 
		'G', '\x2', '\x2', '\x45', '\x46', '\a', '\x43', '\x2', '\x2', '\x46', 
		'G', '\a', '\x46', '\x2', '\x2', 'G', 'H', '\a', '\x41', '\x2', '\x2', 
		'H', '\x6', '\x3', '\x2', '\x2', '\x2', 'I', 'J', '\a', '\x43', '\x2', 
		'\x2', 'J', 'K', '\a', '\x44', '\x2', '\x2', 'K', 'L', '\a', 'Q', '\x2', 
		'\x2', 'L', 'M', '\a', 'T', '\x2', '\x2', 'M', '\b', '\x3', '\x2', '\x2', 
		'\x2', 'N', 'O', '\a', '\x43', '\x2', '\x2', 'O', 'P', '\a', '\x44', '\x2', 
		'\x2', 'P', 'Q', '\a', 'Q', '\x2', '\x2', 'Q', 'R', '\a', 'T', '\x2', 
		'\x2', 'R', 'S', '\a', 'v', '\x2', '\x2', 'S', '\n', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'U', '\x5', '\x13', '\n', '\x2', 'U', 'V', '\x5', '\x19', 
		'\r', '\x2', 'V', 'W', '\x5', '\x35', '\x1B', '\x2', 'W', '\\', '\x3', 
		'\x2', '\x2', '\x2', 'X', 'Y', '\x5', '\x13', '\n', '\x2', 'Y', 'Z', '\x5', 
		'\x35', '\x1B', '\x2', 'Z', '\\', '\x3', '\x2', '\x2', '\x2', '[', 'T', 
		'\x3', '\x2', '\x2', '\x2', '[', 'X', '\x3', '\x2', '\x2', '\x2', '\\', 
		'\f', '\x3', '\x2', '\x2', '\x2', ']', '^', '\x5', '\x13', '\n', '\x2', 
		'^', '_', '\x5', '\x17', '\f', '\x2', '_', '`', '\x5', '\x35', '\x1B', 
		'\x2', '`', '\xE', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x5', 
		'\x15', '\v', '\x2', '\x62', '\x63', '\x5', '\x17', '\f', '\x2', '\x63', 
		'\x64', '\x5', '\x35', '\x1B', '\x2', '\x64', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x66', '\x5', '\x15', '\v', '\x2', '\x66', 'g', '\x5', 
		'\x19', '\r', '\x2', 'g', 'h', '\x5', '\x35', '\x1B', '\x2', 'h', '\x12', 
		'\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '\x45', '\x2', '\x2', 'j', 
		'k', '\a', 'Q', '\x2', '\x2', 'k', 'l', '\a', 'P', '\x2', '\x2', 'l', 
		'm', '\a', 'H', '\x2', '\x2', 'm', 'n', '\a', 'k', '\x2', '\x2', 'n', 
		'o', '\a', 'i', '\x2', '\x2', 'o', 'p', '\a', 'w', '\x2', '\x2', 'p', 
		'q', '\a', 't', '\x2', '\x2', 'q', 'w', '\a', 'g', '\x2', '\x2', 'r', 
		's', '\a', '\x45', '\x2', '\x2', 's', 't', '\a', 'Q', '\x2', '\x2', 't', 
		'u', '\a', 'P', '\x2', '\x2', 'u', 'w', '\a', 'H', '\x2', '\x2', 'v', 
		'i', '\x3', '\x2', '\x2', '\x2', 'v', 'r', '\x3', '\x2', '\x2', '\x2', 
		'w', '\x14', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\a', 'O', '\x2', '\x2', 
		'y', 'z', '\a', 'G', '\x2', '\x2', 'z', '{', '\a', '\x43', '\x2', '\x2', 
		'{', '|', '\a', 'U', '\x2', '\x2', '|', '}', '\a', 'w', '\x2', '\x2', 
		'}', '~', '\a', 't', '\x2', '\x2', '~', '\x84', '\a', 'g', '\x2', '\x2', 
		'\x7F', '\x80', '\a', 'O', '\x2', '\x2', '\x80', '\x81', '\a', 'G', '\x2', 
		'\x2', '\x81', '\x82', '\a', '\x43', '\x2', '\x2', '\x82', '\x84', '\a', 
		'U', '\x2', '\x2', '\x83', 'x', '\x3', '\x2', '\x2', '\x2', '\x83', '\x7F', 
		'\x3', '\x2', '\x2', '\x2', '\x84', '\x16', '\x3', '\x2', '\x2', '\x2', 
		'\x85', '\x86', '\x5', '\x35', '\x1B', '\x2', '\x86', '\x87', '\a', '\x45', 
		'\x2', '\x2', '\x87', '\x88', '\a', 'W', '\x2', '\x2', '\x88', '\x89', 
		'\a', 'T', '\x2', '\x2', '\x89', '\x8A', '\a', 'T', '\x2', '\x2', '\x8A', 
		'\x95', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x8C', '\x5', '\x35', '\x1B', 
		'\x2', '\x8C', '\x8D', '\a', '\x45', '\x2', '\x2', '\x8D', '\x8E', '\a', 
		'W', '\x2', '\x2', '\x8E', '\x8F', '\a', 'T', '\x2', '\x2', '\x8F', '\x90', 
		'\a', 'T', '\x2', '\x2', '\x90', '\x91', '\a', 'g', '\x2', '\x2', '\x91', 
		'\x92', '\a', 'p', '\x2', '\x2', '\x92', '\x93', '\a', 'v', '\x2', '\x2', 
		'\x93', '\x95', '\x3', '\x2', '\x2', '\x2', '\x94', '\x85', '\x3', '\x2', 
		'\x2', '\x2', '\x94', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x95', '\x18', 
		'\x3', '\x2', '\x2', '\x2', '\x96', '\x97', '\x5', '\x35', '\x1B', '\x2', 
		'\x97', '\x98', '\a', 'X', '\x2', '\x2', '\x98', '\x99', '\a', 'Q', '\x2', 
		'\x2', '\x99', '\x9A', '\a', 'N', '\x2', '\x2', '\x9A', '\x9B', '\a', 
		'V', '\x2', '\x2', '\x9B', '\x9C', '\a', '\x63', '\x2', '\x2', '\x9C', 
		'\x9D', '\a', 'i', '\x2', '\x2', '\x9D', '\x9E', '\a', 'g', '\x2', '\x2', 
		'\x9E', '\xA6', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA0', '\x5', '\x35', 
		'\x1B', '\x2', '\xA0', '\xA1', '\a', 'X', '\x2', '\x2', '\xA1', '\xA2', 
		'\a', 'Q', '\x2', '\x2', '\xA2', '\xA3', '\a', 'N', '\x2', '\x2', '\xA3', 
		'\xA4', '\a', 'V', '\x2', '\x2', '\xA4', '\xA6', '\x3', '\x2', '\x2', 
		'\x2', '\xA5', '\x96', '\x3', '\x2', '\x2', '\x2', '\xA5', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA6', '\x1A', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\xA8', '\x5', '\x35', '\x1B', '\x2', '\xA8', '\xA9', '\a', 'V', '\x2', 
		'\x2', '\xA9', '\xAA', '\a', 'G', '\x2', '\x2', '\xAA', '\xAB', '\a', 
		'Z', '\x2', '\x2', '\xAB', '\xAC', '\a', 'V', '\x2', '\x2', '\xAC', '\x1C', 
		'\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\x5', '\x35', '\x1B', '\x2', 
		'\xAE', '\xAF', '\a', 'K', '\x2', '\x2', '\xAF', '\xB0', '\a', 'O', '\x2', 
		'\x2', '\xB0', '\xB1', '\a', 'R', '\x2', '\x2', '\xB1', '\xBE', '\x3', 
		'\x2', '\x2', '\x2', '\xB2', '\xB3', '\x5', '\x35', '\x1B', '\x2', '\xB3', 
		'\xB4', '\a', 'K', '\x2', '\x2', '\xB4', '\xB5', '\a', 'O', '\x2', '\x2', 
		'\xB5', '\xB6', '\a', 'R', '\x2', '\x2', '\xB6', '\xB7', '\a', 'g', '\x2', 
		'\x2', '\xB7', '\xB8', '\a', '\x66', '\x2', '\x2', '\xB8', '\xB9', '\a', 
		'\x63', '\x2', '\x2', '\xB9', '\xBA', '\a', 'p', '\x2', '\x2', '\xBA', 
		'\xBB', '\a', '\x65', '\x2', '\x2', '\xBB', '\xBC', '\a', 'g', '\x2', 
		'\x2', '\xBC', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xBD', '\xAD', '\x3', 
		'\x2', '\x2', '\x2', '\xBD', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xBE', 
		'\x1E', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC0', '\a', '\x43', '\x2', 
		'\x2', '\xC0', '\xC1', '\a', '\x45', '\x2', '\x2', '\xC1', ' ', '\x3', 
		'\x2', '\x2', '\x2', '\xC2', '\xC3', '\a', '\x46', '\x2', '\x2', '\xC3', 
		'\xC4', '\a', '\x45', '\x2', '\x2', '\xC4', '\"', '\x3', '\x2', '\x2', 
		'\x2', '\xC5', '\xC6', '\a', '\x43', '\x2', '\x2', '\xC6', '\xC7', '\a', 
		'W', '\x2', '\x2', '\xC7', '\xC8', '\a', 'V', '\x2', '\x2', '\xC8', '\xC9', 
		'\a', 'Q', '\x2', '\x2', '\xC9', '$', '\x3', '\x2', '\x2', '\x2', '\xCA', 
		'\xCB', '\a', 'O', '\x2', '\x2', '\xCB', '\xCC', '\a', 'K', '\x2', '\x2', 
		'\xCC', '\xCD', '\a', 'P', '\x2', '\x2', '\xCD', '&', '\x3', '\x2', '\x2', 
		'\x2', '\xCE', '\xCF', '\a', 'O', '\x2', '\x2', '\xCF', '\xD0', '\a', 
		'\x43', '\x2', '\x2', '\xD0', '\xD1', '\a', 'Z', '\x2', '\x2', '\xD1', 
		'(', '\x3', '\x2', '\x2', '\x2', '\xD2', '\xD3', '\a', '\x46', '\x2', 
		'\x2', '\xD3', '\xD4', '\a', 'G', '\x2', '\x2', '\xD4', '\xD5', '\a', 
		'H', '\x2', '\x2', '\xD5', '*', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', 
		'\a', '\"', '\x2', '\x2', '\xD7', ',', '\x3', '\x2', '\x2', '\x2', '\xD8', 
		'\xDA', '\x5', '+', '\x16', '\x2', '\xD9', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xDA', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xD9', '\x3', 
		'\x2', '\x2', '\x2', '\xDB', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDC', 
		'.', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\a', '.', '\x2', '\x2', 
		'\xDE', '\x30', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE1', '\x5', '-', 
		'\x17', '\x2', '\xE0', '\xDF', '\x3', '\x2', '\x2', '\x2', '\xE0', '\xE1', 
		'\x3', '\x2', '\x2', '\x2', '\xE1', '\xE2', '\x3', '\x2', '\x2', '\x2', 
		'\xE2', '\xE4', '\x5', '/', '\x18', '\x2', '\xE3', '\xE5', '\x5', '-', 
		'\x17', '\x2', '\xE4', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE4', '\xE5', 
		'\x3', '\x2', '\x2', '\x2', '\xE5', '\x32', '\x3', '\x2', '\x2', '\x2', 
		'\xE6', '\xE7', '\a', '\x41', '\x2', '\x2', '\xE7', '\x34', '\x3', '\x2', 
		'\x2', '\x2', '\xE8', '\xE9', '\a', '<', '\x2', '\x2', '\xE9', '\x36', 
		'\x3', '\x2', '\x2', '\x2', '\xEA', '\xF2', '\x5', ';', '\x1E', '\x2', 
		'\xEB', '\xEC', '\x5', ';', '\x1E', '\x2', '\xEC', '\xED', '\a', '\x30', 
		'\x2', '\x2', '\xED', '\xEF', '\x5', ';', '\x1E', '\x2', '\xEE', '\xF0', 
		'\x5', '\x39', '\x1D', '\x2', '\xEF', '\xEE', '\x3', '\x2', '\x2', '\x2', 
		'\xEF', '\xF0', '\x3', '\x2', '\x2', '\x2', '\xF0', '\xF2', '\x3', '\x2', 
		'\x2', '\x2', '\xF1', '\xEA', '\x3', '\x2', '\x2', '\x2', '\xF1', '\xEB', 
		'\x3', '\x2', '\x2', '\x2', '\xF2', '\x38', '\x3', '\x2', '\x2', '\x2', 
		'\xF3', '\xFD', '\t', '\x2', '\x2', '\x2', '\xF4', '\xF5', '\a', 'g', 
		'\x2', '\x2', '\xF5', '\xFD', '\a', '-', '\x2', '\x2', '\xF6', '\xF7', 
		'\a', 'G', '\x2', '\x2', '\xF7', '\xFD', '\a', '-', '\x2', '\x2', '\xF8', 
		'\xF9', '\a', 'g', '\x2', '\x2', '\xF9', '\xFD', '\a', '/', '\x2', '\x2', 
		'\xFA', '\xFB', '\a', 'G', '\x2', '\x2', '\xFB', '\xFD', '\a', '/', '\x2', 
		'\x2', '\xFC', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xF4', '\x3', 
		'\x2', '\x2', '\x2', '\xFC', '\xF6', '\x3', '\x2', '\x2', '\x2', '\xFC', 
		'\xF8', '\x3', '\x2', '\x2', '\x2', '\xFC', '\xFA', '\x3', '\x2', '\x2', 
		'\x2', '\xFD', '\xFF', '\x3', '\x2', '\x2', '\x2', '\xFE', '\x100', '\x4', 
		'\x32', ';', '\x2', '\xFF', '\xFE', '\x3', '\x2', '\x2', '\x2', '\x100', 
		'\x101', '\x3', '\x2', '\x2', '\x2', '\x101', '\xFF', '\x3', '\x2', '\x2', 
		'\x2', '\x101', '\x102', '\x3', '\x2', '\x2', '\x2', '\x102', ':', '\x3', 
		'\x2', '\x2', '\x2', '\x103', '\x105', '\x4', '\x32', ';', '\x2', '\x104', 
		'\x103', '\x3', '\x2', '\x2', '\x2', '\x105', '\x106', '\x3', '\x2', '\x2', 
		'\x2', '\x106', '\x104', '\x3', '\x2', '\x2', '\x2', '\x106', '\x107', 
		'\x3', '\x2', '\x2', '\x2', '\x107', '<', '\x3', '\x2', '\x2', '\x2', 
		'\x11', '\x2', '[', 'v', '\x83', '\x94', '\xA5', '\xBD', '\xDB', '\xE0', 
		'\xE4', '\xEF', '\xF1', '\xFC', '\x101', '\x106', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace ProtocolParser.Keysight3458A
