//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Develop\Open-SCPI-Protocol-Emulator\ProtocolParser\Keysight34465A\Keysight34465ASCPI.g4 by ANTLR 4.9.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ProtocolParser.Keysight34465A {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Keysight34465ASCPIParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.1")]
[System.CLSCompliant(false)]
public interface IKeysight34465ASCPIVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCommand([NotNull] Keysight34465ASCPIParser.CommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.identificationQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentificationQuery([NotNull] Keysight34465ASCPIParser.IdentificationQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.readQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReadQuery([NotNull] Keysight34465ASCPIParser.ReadQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.abortCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAbortCommand([NotNull] Keysight34465ASCPIParser.AbortCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.configureCurrentCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfigureCurrentCommand([NotNull] Keysight34465ASCPIParser.ConfigureCurrentCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.configureVoltageCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConfigureVoltageCommand([NotNull] Keysight34465ASCPIParser.ConfigureVoltageCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.measureCurrentQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeasureCurrentQuery([NotNull] Keysight34465ASCPIParser.MeasureCurrentQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.measureVoltageQuery"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMeasureVoltageQuery([NotNull] Keysight34465ASCPIParser.MeasureVoltageQueryContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.displayTextCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisplayTextCommand([NotNull] Keysight34465ASCPIParser.DisplayTextCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.displayTextClearCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDisplayTextClearCommand([NotNull] Keysight34465ASCPIParser.DisplayTextClearCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.senseVoltageImpedanceCommand"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSenseVoltageImpedanceCommand([NotNull] Keysight34465ASCPIParser.SenseVoltageImpedanceCommandContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.currentParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCurrentParameters([NotNull] Keysight34465ASCPIParser.CurrentParametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Keysight34465ASCPIParser.voltageParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVoltageParameters([NotNull] Keysight34465ASCPIParser.VoltageParametersContext context);
}
} // namespace ProtocolParser.Keysight34465A
